/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const LucideGithub: typeof import('~icons/lucide/github').default
  const LucideLinkedin: typeof import('~icons/lucide/linkedin').default
  const LucideTwitter: typeof import('~icons/lucide/twitter').default
}
