pull_request_rules:
    - name: backport to develop
      conditions:
          - label="backport develop"
      actions:
          backport:
              branches:
                  - develop
              assignees:
                  - "{{ author }}"

    - name: backport to main-hotfix
      conditions:
          - label="backport main-hotfix"
      actions:
          backport:
              branches:
                  - main-hotfix
              assignees:
                  - "{{ author }}"

    - name: backport to main
      conditions:
          - label="backport main"
      actions:
          backport:
              branches:
                  - main
              assignees:
                  - "{{ author }}"

    - name: backport to version-15-hotfix
      conditions:
          - label="backport version-15-hotfix"
      actions:
          backport:
              branches:
                  - version-15-hotfix
              assignees:
                  - "{{ author }}"

    - name: backport to version-16-hotfix
      conditions:
          - label="backport version-16-hotfix"
      actions:
          backport:
              branches:
                  - version-16-hotfix
              assignees:
                  - "{{ author }}"

    - name: backport to version-17-hotfix
      conditions:
          - label="backport version-17-hotfix"
      actions:
          backport:
              branches:
                  - version-17-hotfix
              assignees:
                  - "{{ author }}"

    - name: backport to all hotfix lines
      conditions:
          - label="backport all-hotfixes"
      actions:
          backport:
              branches:
                  - version-15-hotfix
                  - version-16-hotfix
                  - version-17-hotfix
              assignees:
                  - "{{ author }}"
