coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%

ignore:
  # --- Tus exclusiones globales originales ---
  - "**/test_*.py"  
  - "**/__init__.py"
  - "**/hooks.py"
  - "**/install.py"
  - "**/activation.py"
  - "**/onboarding.py"
  - "**/notification/*"
  - "lms/job/notification/new_job_alert/new_job_alert.py"
  - "lms/job/web_form/job_opportunity/job_opportunity.py"
  - "lms/lms/doctype/function/function.py"
  - "lms/lms/doctype/industry/industry.py"
  - "lms/lms/doctype/lms_batch_feedback/lms_batch_feedback.py"
  - "lms/lms/doctype/lms_category/lms_category.py"
  - "lms/lms/doctype/lms_coupon_item/lms_coupon_item.py"
  - "lms/lms/doctype/lms_lesson_note/lms_lesson_note.py"
  - "lms/lms/doctype/lms_live_class_participant/lms_live_class_participant.py"
  - "lms/lms/doctype/lms_option/lms_option.py"
  - "lms/lms/doctype/lms_program_course/lms_program_course.py"
  - "lms/lms/doctype/lms_program_member/lms_program_member.py"
  - "lms/lms/doctype/lms_sidebar_item/lms_sidebar_item.py"
  - "lms/lms/doctype/lms_source/lms_source.py"
  - "lms/lms/doctype/lms_timetable_template/lms_timetable_template.py"
  - "lms/lms/doctype/lms_video_watch_duration/lms_video_watch_duration.py"
  - "lms/lms/doctype/lms_zoom_settings/lms_zoom_settings.py"
  - "lms/lms/doctype/payment_country/payment_country.py"
  - "lms/lms/doctype/scheduled_flow/scheduled_flow.py"
  - "lms/lms/doctype/user_skill/user_skill.py"
  - "lms/lms/doctype/zoom_settings/zoom_settings.py"
  - "lms/lms/doctype/lms_course_interest/lms_course_interest.py"

  - "lms/lms/doctype/lms_certificate_request/lms_certificate_request.py"
  - "lms/plugins.py"
  - "lms/command_palette.py"
  - "lms/payments.py"
  - "lms/lms/payments.py"
  - "lms/lms/doctype/lms_payment/lms_payment.py"
  - "lms/page_renderers.py"
  - "lms/lms/doctype/lms_program/lms_program.py"
  - "lms/lms/report/course_progress_summary/course_progress_summary.py"
  - "lms/job/doctype/job_opportunity/job_opportunity.py"
  
  - "lms/lms/doctype/course_lesson/course_lesson.py"
  - "lms/sqlite.py"
  - "lms/user.py"
