coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%

ignore:
  - "**/test_*.py"  
  - "**/__init__.py"
  - "**/hooks.py"
  - "**/install.py"
  - "**/test_*.py"
  - "**/activation.py"
  - "**/onboarding.py"
  - "**/notification/*"