/**
 * Every icon the palette names must exist in lucide.
 *
 * Icons are `lucide-*` classes generated by the frappe-ui vite plugin from
 * lucide-static, the way the rest of the app names them. The names still have
 * to be real: a class that generates nothing renders an empty box, silently.
 *
 * This guard arrived because the imported-component form failed harder and
 * later — `House` is lucide's post-0.400 name for `Home` and this bench is on
 * 0.383, so the browser's strict ESM refused the module and the palette died on
 * load while every suite stayed green, vitest's interop having handed back
 * `undefined` for the missing export.
 */
import { existsSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { CATEGORIES, NAV_TARGETS } from '@/components/CommandPalette/categories'

const ICON_DIR = join(
	dirname(createRequire(import.meta.url).resolve('lucide-static/package.json')),
	'icons'
)

const rows = [...CATEGORIES, ...NAV_TARGETS].map(({ label, icon }) => ({
	label,
	icon,
}))

describe('command palette icons', () => {
	it.each(rows)('$label uses a real lucide icon: $icon', ({ icon }) => {
		expect(icon).toMatch(/^lucide-[a-z0-9-]+$/)
		expect(existsSync(join(ICON_DIR, `${icon.slice(7)}.svg`))).toBe(true)
	})

	// The Settings row is built in the component, not in categories.ts.
	it('names a real icon for the Settings row', () => {
		expect(existsSync(join(ICON_DIR, 'settings.svg'))).toBe(true)
	})
})
