files:
  - source: /lms/locale/main.pot
    translation: /lms/locale/%two_letters_code%.po
pull_request_title: "chore: sync translations from crowdin"
pull_request_labels:
  - translation
commit_message: "chore: %language% translations"
append_commit_message: false